config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :reviews
  end

  namespace :api, format: :json do
    namespace :v1 do
      namespace :cuisines do
        get 'get_all_cuisines'
      end

    end
  end

  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '(*path)', to: 'application#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /restaurants/:restaurant_id/reviews
  # GET /restaurants/:restaurant_id/reviews.json
  def index
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you get all the reviews of this restaurant
    @reviews = restaurant.reviews

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @reviews }
    end
  end

  # GET /restaurants/:restaurant_id/reviews/:id
  # GET /reviews/:id.json
  def show
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you retrieve the review thanks to params[:id]
    @review = restaurant.reviews.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @reviews }
    end
  end

  # GET /restaurants/:restaurant_id/reviews/new
  # GET /restaurants/:restaurant_id/reviews/new.json
  def new
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you build a new one
    @review = restaurant.reviews.build

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @reviews }
    end
  end

  # GET /restaurants/:restaurant_id/reviews/:id/edit
  def edit
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you retrieve the review thanks to params[:id]
    @review = restaurant.reviews.find(params[:id])
  end

  # POST /restaurants/:restaurant_id/reviews
  # POST /restaurants/:restaurant_id/reviews.json
  def create
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you create the review with arguments in params[:reviews]
    @review = restaurant.reviews.create!(review_params)

    respond_to do |format|
      if @review.save
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource review
        format.html { redirect_to([@review.restaurant, @review], notice: 'Review was successfully created.') }
        #the key :location is associated to an array in order to build the correct route to the nested resource review
        format.json  { render :json => @review, status: :created, location: [@review.restaurant, @review] }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/:restaurant_id/reviews/:id
  # PUT /restaurants/:restaurant_id/reviews/:id.json
  def update
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you retrieve the review thanks to params[:id]
    @review = restaurant.reviews.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(review_params)
        #1st argument of redirect_to is an array, in order to build the correct route to the nested resource review
        format.html { redirect_to([@review.restaurant, @review], :notice => 'Review was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @review.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/:restaurant_id/reviews/1
  # DELETE /restaurants/:restaurant_id/reviews/1.json
  def destroy
    #1st you retrieve the restaurant thanks to params[:restaurant_id]
    restaurant = find_restaurant
    #2nd you retrieve the review thanks to params[:id]
    @review = restaurant.reviews.find(params[:id])
    @review.destroy

    respond_to do |format|
      #1st argument reference the path /restaurants/:restaurant_id/reviews/
      format.html { redirect_to(restaurant_reviews_url) }
      format.json  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :date, :restaurant_id)
    end

    def find_restaurant
      Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@review.restaurant, @review]) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, id: :review_rating, in: 0...4 %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :review_comment %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :review_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', [@review.restaurant, @review] %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>Date</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.date %></td>
        <td><%= review.restaurant_id %></td>
        <td><%= link_to 'Show', [review.restaurant, review] %></td>
        <td><%= link_to 'Edit', edit_restaurant_review_path(review.restaurant, review) %></td>
        <td><%= link_to 'Destroy', [review.restaurant, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_restaurant_review_path %>
<%= link_to 'Restaurants', restaurants_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Date:</strong>
  <%= @review.date %>
</p>

<%= link_to 'Edit', edit_restaurant_review_path(@review.restaurant, @review) %> |
<%= link_to 'Back', restaurant_reviews_path(@review.restaurant) %>